DROP TABLE USUARIOS;
DROP TABLE TRANSFERENCIAS;


CREATE TABLE USUARIOS (
	ID SERIAL PRIMARY KEY,
	NOMBRE VARCHAR (50),
	BALANCE FLOAT CHECK (balance >= 0)

);

CREATE TABLE TRANSFERENCIAS (
	id SERIAL PRIMARY KEY,
	emisor INT,
	receptor INT,
	monto FLOAT,
	fecha TIMESTAMP,
	FOREIGN KEY (emisor) REFERENCES
usuarios(id), FOREIGN KEY (receptor) REFERENCES usuarios(id)

);

INSERT INTO USUARIOS (NOMBRE, BALANCE) VALUES ('USUARIO1', 1000);
INSERT INTO USUARIOS (NOMBRE, BALANCE) VALUES ('USUARIO2', 100);

SELECT * FROM USUARIOS;
SELECT * FROM TRANSFERENCIAS;

INSERT INTO TRANSFERENCIAS (emisor, receptor, monto, fecha) VALUES (1, 2, 500, CURRENT_TIMESTAMP);

