DROP TABLE IF EXISTS USUARIOS;
DROP TABLE IF EXISTS TRANSFERENCIAS;

CREATE TABLE USUARIOS (
    ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(50),
    BALANCE DECIMAL(10, 2) CHECK (BALANCE >= 0)
);

CREATE TABLE TRANSFERENCIAS (
    ID SERIAL PRIMARY KEY,
    EMISOR INT,
    FOREIGN KEY(EMISOR) REFERENCES USUARIOS(ID),
    RECEPTOR INT,
    FOREIGN KEY(RECEPTOR) REFERENCES USUARIOS(ID),
    MONTO INT CHECK(MONTO > 0),
    FECHA TIMESTAMP
);

INSERT INTO USUARIOS (NOMBRE, BALANCE) VALUES ('ANA', 1000);
INSERT INTO USUARIOS (NOMBRE, BALANCE) VALUES ('LUISA', 100);

SELECT * FROM USUARIOS;
SELECT * FROM TRANSFERENCIAS;

INSERT INTO TRANSFERENCIAS (emisor, receptor, monto, fecha) VALUES (1, 2, 500, CURRENT_TIMESTAMP);
INSERT INTO TRANSFERENCIAS (emisor, receptor, monto, fecha) VALUES (2, 1, 100, CURRENT_TIMESTAMP);


